[package]
name = "chia-vanity-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
bip39 = "2.2.0"
chia-bls = "0.36.1"
chia-puzzle-types = "0.36.1"
chia-sdk-types = { path = "../external/chia-wallet-sdk/crates/chia-sdk-types" }
chia-sdk-utils = { path = "../external/chia-wallet-sdk/crates/chia-sdk-utils" }
clap = { version = "4.5.50", features = ["derive"] }
hex = "0.4"
