[package]
name = "chia-vanity-sdk"
version = "0.1.0"
edition = "2021"

[lib]
name = "chia_vanity"
path = "src/lib.rs"

[features]
default = ["native-cli"]
native-cli = ["dep:chia-wallet-sdk"]

[dependencies]
anyhow = "1"
bip39 = "2.2.0"
rayon = "1.10"
chia-wallet-sdk = { version = "0.33.0", optional = true }

[[bin]]
name = "chia-vanity-sdk"
path = "src/main.rs"
required-features = ["native-cli"]
